### ISSUE TITLE
Request align environment support.

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#15]
![2021-08-28_15-24-36](https://user-images.githubusercontent.com/80107081/131210266-45e793c9-d094-4d0a-8e5e-cca563c81a6e.png)
![2021-08-28_15-25-34](https://user-images.githubusercontent.com/80107081/131210270-1ab0765f-f9a6-4d0f-b586-e0e67be42373.png)

`aligned` environment works but `align` environment doesn't.

Here is the test code.

```markdown
$$\begin{align}a&=1\\bc&=1\end{align}$$

$$\begin{align}a=1\\bc=1\end{align}$$

$$\begin{aligned}a&=1\\bc&=1\end{aligned}$$

$$\begin{aligned}a=1\\bc=1\end{aligned}$$
```

**Comment by Jwrede** [comment]
Hi, this is a problem with KaTeX itself, the error is known but there seems to be no fix for it (https://katex.org/docs/issues.html 4th bullet and https://github.com/KaTeX/KaTeX/issues/1007). 
I don't know why they think `aligned` is a replacement for `align` because `aligned` doesn't provide the numbering which is especially important for math cards but sadly I can't change anything internal in KaTeX.

**Comment by pilgrimlyieu** [comment]
> Hi, this is a problem with KaTeX itself, the error is known but there seems to be no fix for it (https://katex.org/docs/issues.html 4th bullet and [KaTeX/KaTeX#1007](https://github.com/KaTeX/KaTeX/issues/1007)).
> I don't know why they think `aligned` is a replacement for `align` because `aligned` doesn't provide the numbering which is especially important for math cards but sadly I can't change anything internal in KaTeX.

OK. Thanks you. But I can use align environment through KaTeX in VSCode.😂

**Comment by Jwrede** [comment]
Yea same, I'm pretty sure the problem lies in the auto-render addon for KaTeX which I'm using and the VSCode markdown plugin uses its own renderer
