### ISSUE TITLE
Where to store persistent KaTex macros 

### ISSUE THREAD

**Issue by toomey8** [Jwrede/Anki-KaTeX-Markdown#6]
This is fantastic! Apologies as this is something of an edge case but I make extensive use of 
[KaTex macros](https://katex.org/docs/options.html). 

I can define them on the cards themselves, i.e. placing `$\gdef{\foo}{x^2}$` on the card itself, but wonder if you know where in the template one could store these (I have 40 or so I make regular use of) and if it's possible to extend support for macros in general. 

For reference:

- Someone doing this for a static site generator [here](https://vincenttam.gitlab.io/post/2018-09-27-custom-katex-macros/)
- KaTex itself defines some custom macros [here](https://github.com/KaTeX/KaTeX/blob/master/src/macros.js)

I'm having trouble parsing if these should be in a script tag, wrapped in `$...$` in a `\gdef` etc. Any pointers?

Thanks again, this is a fantastic plugin!

**Comment by Jwrede** [comment]
![image](https://user-images.githubusercontent.com/62910358/116012012-3e5b3700-a628-11eb-90bd-c51d138f69bf.png)
I marked the region where you can put your macros, remember to always put a double backslash!

One problem is that you'll have to do a copy of the card template because if I update the Add-on the Card template will change. That's one thing I'll definitly have to improve, maybe I'll add a text file to the add-on where you can add macros, there are some other bugs i'll have to fix as well but I've got a pretty intense uni phase right now so this'll probably take one or two weeks, I hope this is enough for now.
If you need help with creating a copy of the template please tell me!

**Comment by toomey8** [comment]
thanks! this works like a charm. I was able to get this to work. I'm not sure how much of an edge case defining macros but I agree that it would be nice to have an external plain text file for them. That's what I'm maintaining anyway, and it's not too much of a bother. 

Thanks, again, this is perfect!
